#! usr/bin/perl

print "please give me a width?";
chomp(my $width = <STDIN>);

print "type some lines then crtl-d\n";
chomp(my @lines = <STDIN>);

print "1234567890" x (($width+9)/10), "\n";

foreach(@lines){
	printf "%${width}s\n", $_;
}
